WP/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WP.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminHomeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

WP/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WP.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WP.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        // GET: /<controller>/
        readonly private WebAppContext _context;
        public CartVM cartVM { get; set; }

        public CartController(WebAppContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            cartVM = new CartVM()
            {
                ListCarts = await _context.ShoppingCarts.Where(m => m.UserId == claim.Value).Include(p => p.User).Include(a => a.Product).ToListAsync(),
                CartTotal = CartTotal()

            };

            var list = await _context.ShoppingCarts.Where(m => m.UserId == claim.Value).ToListAsync();
            var count = list.Count;
            ViewData["count"] = count;

            return View(cartVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddProducttoCart(ShoppingCart shoppingCart)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            shoppingCart.UserId = claim.Value;

            ShoppingCart cartFromDb = _context.ShoppingCarts.FirstOrDefault(u => u.UserId == claim.Value && u.ProductId == shoppingCart.ProductId);
            if (cartFromDb == null)
            {
                _context.ShoppingCarts.Add(shoppingCart);
            }
            else
            {
                cartFromDb.Count += shoppingCart.Count;
                if (cartFromDb.Count < 0)
                {
                    TempData["failed"] = "Count can not be lower than 0";
                    return RedirectToAction("DetailedProducts", "Home", new { id = shoppingCart.ProductId });
                }

                _context.Update(cartFromDb);
            }



            _context.SaveChanges();

            TempData["success"] = "You have added a product to cart";

            return RedirectToAction("DetailedProducts", "Home", new { id = shoppingCart.ProductId });

        }


        public int CartTotal()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var UserId = claim.Value;
            var shoppingList = _context.ShoppingCarts.Where(m => m.UserId == claim.Value).Include(p => p.User).Include(a => a.Product).ToList();

            int cartTotal = 0;
            foreach (var item in shoppingList)
            {
                cartTotal += item.Count * item.Product.Price;
            };

            return cartTotal;

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RemoveFromCart(int id)
        {
            var cart = _context.ShoppingCarts.Find(id);
            _context.ShoppingCarts.Remove(cart);
            _context.SaveChanges();
            TempData["success"] = "You have been deleted this product succesfully";
            return RedirectToAction("Index", "Home");


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult OrderProducts()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var userID = claim.Value;
            if (userID is not null)
            {
                var list = _context.ShoppingCarts.Where(a => a.UserId == userID).ToList();
                foreach (var item in list)
                {
                    _context.ShoppingCarts.Remove(item);
                }
                _context.SaveChanges();
                TempData["success"] = "You have been ordered succesfuly";
            }
            else
            {
                NotFound();
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

WP/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
    </style>
    <title>@ViewData["Title"] - WP</title>
    <partial name="_StylesFiles" />
</head>
<body>


    @if (!User.IsInRole("Admin"))
    {
        <partial name="_UserNavbar" />
    }



    <div class="wrapper d-flex align-items-stretch">

        @if (User.IsInRole("Admin"))
        {
            <partial name="_UserNavbar" />
        }

        <div class="" style="width:100%">
            <main role="main" class="pb-3">
                <partial name="_Notification" />
                @RenderBody()
            </main>
        </div>

        <partial name="_ScriptsFiles" />
        @await RenderSectionAsync("Scripts", required: false)
    </div>
</body>
</html>

WP/Views/Shared/_Navbar.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<nav id="sidebar" style="height:1000px;">
    <div class="p-4 pt-5">
        <div class="container">
            <div class="row">
                <a asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="img logo rounded-circle" src="~/img/admin.gif" runat="server" />
                </a>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-md-12 ml-5">
                    <a id="manage" class="nav-link" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage" style="color:white;">@UserManager.GetUserName(User)</a>
                </div>
            </div>
        </div>
        <ul class="list-unstyled components mb-5 mt-5">
            <li class="active">
                <a asp-area="" asp-controller="AdminHome" asp-action="Index" aria-expanded="false">Home</a>
            </li>
            <li class="">
                <a asp-area="" asp-controller="Category" asp-action="Create" aria-expanded="false">Category</a>
            </li>
            <li>
                <a asp-area="" asp-action="Index" asp-controller="Category">Category List</a>
            </li>
            <li>
                <a asp-area="" asp-action="Create" asp-controller="Product">Product Create</a>
            </li>
            <li>
                <a asp-area="" asp-action="Index" asp-controller="Product">Product List</a>
            </li>
            <li>
                <a asp-area="" asp-action="Index" asp-controller="Home">User Home</a>
            </li>
            <li class="nav-item d-flex justify-content-center mt-5" style="margin-top:auto;">
                <div class="mt-5">
                    <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                        <button id="logout" type="submit" class="nav-link btn btn-link text-dark" style="color:white !important;">
                            <i class="bi bi-box-arrow-right"></i>
                            Logout
                        </button>
                    </form>
                </div>
            </li>
            <br />
            <br />



        </ul>

    </div>
</nav>

WP/Views/Shared/_ScriptsFiles.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/js/main.js"></script>
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

WP/Views/Shared/_StylesFiles.cshtml
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
<link rel="stylesheet" href="~/css/sidebar.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

WP/Views/Shared/_UserNavbar.cshtml
@using Microsoft.AspNetCore.Identity
@inject ILanguageService language

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<header class="section-header">
    @if (User.IsInRole("Admin"))
    {
        <partial name="_Navbar" />
    }
    else
    {


        <section class="header-main border-bottom bg-white mt-0 p-3">
            <div class="container-fluid">
                <div class="row p-2 pt-3 pb-3 d-flex align-items-center">
                    <div class="col-md-2 d-flex justify-content-center">
                        <a asp-controller="Home" asp-action="Index">
                            <i class="bi bi-cart-check-fill" style="font-size: 45px;color: #5d18eb">
                            </i>
                        </a>
                    </div>
                    <div class="col-md-5">
                        <form asp-action="Index" asp-controller="Home" method="get">

                            <div class="row d-flex form-inputs justify-content-center align-items-center">

                                <div class="col-md-8">
                                    <input type="text" class="form-control form-input" placeholder="Search Products" name="search" value="@ViewData["currentSearch"]" style="width:100%;border-radius:8px;border:1px solid gray" />
                                </div>
                                <div class="col-md-4">
                                    <input type="submit" name="Search" class="btn" value="Search" style="background-color:#5d18eb;color:white" />
                                </div>

                            </div>
                        </form>
                    </div>


                    <div class="col-md-3 d-flex justify-content-center">
                        <div class="d-flex d-none d-md-flex flex-row align-items-center">
                            <i class="bi bi-person" style="font-size:30px"></i>
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <a id="manage" class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage" style="font-weight:bold;">@UserManager.GetUserName(User)</a>

                                <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                    <button id="logout" type="submit" class="nav-link btn btn-link text-dark">@language.Getkey("Logout")</button>
                                </form>
                            }
                            else
                            {
                                <a class="nav-link text-dark" id="register" asp-area="Identity" asp-page="/Account/Register">@language.Getkey("Register")</a>
                                <a class="nav-link text-dark" id="login" asp-area="Identity" asp-page="/Account/Login">@language.Getkey("Login")</a>
                            }
                            <div class="row">
                                <div class="col-lg-12 dropdown">
                                    <div class="dropdown">
                                        <i class="bi bi-globe-americas dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" style="font-size:30px;margin-left:1em;"></i>
                                        <ul class="dropdown-menu">

                                            <li><a style="color:black" asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="en-US" class="nav-link"> @language.Getkey("English")</a></li>

                                            <li><a style="color:black" asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="es-ES" class="nav-link"> @language.Getkey("Español")</a></li>

                                            <li><a style="color:black" asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="ja-JP" class="nav-link"> @language.Getkey("Japanese")</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-2 d-flex justify-content-center">
                        <div class="d-flex d-none d-md-flex flex-row align-items-center">
                            <a asp-controller="Cart" asp-action="Index"><span class="shop-bag"><i class="bi bi-basket-fill"></i></span></a>
                            <div class="d-flex flex-column ms-2">
                                <span class="qty"><a asp-controller="Cart" asp-action="Index" style="color:black;font-size:20px">@language.Getkey("Cart")</a></span>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    }
</header>