WP/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WP.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WP.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        // GET: /<controller>/
        readonly private WebAppContext _context;
        public CartVM cartVM { get; set; }

        public CartController(WebAppContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            cartVM = new CartVM()
            {
                ListCarts = await _context.ShoppingCarts.Where(m => m.UserId == claim.Value).Include(p => p.User).Include(a => a.Product).ToListAsync(),
                CartTotal = CartTotal()

            };

            var list = await _context.ShoppingCarts.Where(m => m.UserId == claim.Value).ToListAsync();
            var count = list.Count;
            ViewData["count"] = count;

            return View(cartVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddProducttoCart(ShoppingCart shoppingCart)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            shoppingCart.UserId = claim.Value;

            ShoppingCart cartFromDb = _context.ShoppingCarts.FirstOrDefault(u => u.UserId == claim.Value && u.ProductId == shoppingCart.ProductId);
            if (cartFromDb == null)
            {
                _context.ShoppingCarts.Add(shoppingCart);
            }
            else
            {
                cartFromDb.Count += shoppingCart.Count;
                if (cartFromDb.Count < 0)
                {
                    TempData["failed"] = "Count can not be lower than 0";
                    return RedirectToAction("DetailedProducts", "Home", new { id = shoppingCart.ProductId });
                }

                _context.Update(cartFromDb);
            }



            _context.SaveChanges();

            TempData["success"] = "You have added a product to cart";

            return RedirectToAction("DetailedProducts", "Home", new { id = shoppingCart.ProductId });

        }


        public int CartTotal()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var UserId = claim.Value;
            var shoppingList = _context.ShoppingCarts.Where(m => m.UserId == claim.Value).Include(p => p.User).Include(a => a.Product).ToList();

            int cartTotal = 0;
            foreach (var item in shoppingList)
            {
                cartTotal += item.Count * item.Product.Price;
            };

            return cartTotal;

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RemoveFromCart(int id)
        {
            var cart = _context.ShoppingCarts.Find(id);
            _context.ShoppingCarts.Remove(cart);
            _context.SaveChanges();
            TempData["success"] = "You have been deleted this product succesfully";
            return RedirectToAction("Index", "Home");


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult OrderProducts()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var userID = claim.Value;
            if (userID is not null)
            {
                var list = _context.ShoppingCarts.Where(a => a.UserId == userID).ToList();
                foreach (var item in list)
                {
                    _context.ShoppingCarts.Remove(item);
                }
                _context.SaveChanges();
                TempData["success"] = "You have been ordered succesfuly";
            }
            else
            {
                NotFound();
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

WP/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WP.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WP.Controllers
{
    public class CommentController : Controller
    {
        readonly private WebAppContext _context;

        public CommentController(WebAppContext context)
        {
            _context = context;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult AddCommentToProduct(Comment comment, string context)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            comment.UserId = claim.Value;

            _context.Comments.Add(comment);
            _context.SaveChanges();

            TempData["success"] = "You has been added a comment for this product";

            return RedirectToAction("DetailedProducts", "Home", new { id = comment.ProductId });

        }
    }
}

WP/Controllers/HomeController.cs
using System.Diagnostics;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WP.Models;

namespace WP.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    readonly private WebAppContext _context;

    public HomeController(ILogger<HomeController> logger, WebAppContext context)
    {
        _logger = logger;
        _context = context;
    }



    public IActionResult Index(string? bname,string? search)
    {
        CategoriesProducts cp = new CategoriesProducts();
        var categoryObject = cp.categories;
        var productObject = cp.products;
        categoryObject = _context.Categories.ToList();
        ViewData["currentSearch"] = search;
        if (search != null)
        {
            if (bname != null)
            {
                if (bname == "Ascending")
                {
                    productObject = _context.Products.Where(x=>x.Title.Contains(search)).OrderBy(y => y.Price).ToList();
                }
                if (bname == "Descending")
                {
                    productObject = _context.Products.Where(x => x.Title.Contains(search)).OrderByDescending(y => y.Price).ToList();
                }
            }
            else
            {
                productObject = _context.Products.Where(x => x.Title.Contains(search)).OrderBy(y=>y.Title).ToList();
            }
        }
        else
        {
            if (bname != null)
            {
                if (bname == "Ascending")
                {
                    productObject = (from y in _context.Products select y).OrderBy(y => y.Price).ToList();
                }
                if (bname == "Descending")
                {
                    productObject = (from y in _context.Products select y).OrderByDescending(y => y.Price).ToList();
                }
            }
            else
            {
                productObject = (from y in _context.Products select y).OrderBy(y => y.Title).ToList();
            }
        }
        
        cp.products = productObject;
        cp.categories = categoryObject;
        return View(cp);
    }
   
    public IActionResult FilteredProducts(int id,string? bname)
    {
        CategoriesProducts cp2 = new CategoriesProducts();
        var categoryObject = cp2.categories;
        var filteredproducts = cp2.products;
        ViewData["categoryid"] = id;
        if (bname != null)
        {
            if (bname == "Ascending")
            {
                filteredproducts = _context.Products.Where(x => x.CategoryId == id).OrderBy(y => y.Price).ToList();
            }
            if (bname == "Descending")
            {
                filteredproducts = _context.Products.Where(x => x.CategoryId == id).OrderByDescending(y => y.Price).ToList();
            }
        }
        else
        {
            filteredproducts = _context.Products.Where(x => x.CategoryId == id).ToList();
        }
        categoryObject = _context.Categories.ToList();
        var name = _context.Categories.Where(x => x.CategoryId == id).FirstOrDefault();
        ViewData["name"] = name.CategoryName;
        cp2.products = filteredproducts;
        cp2.categories = categoryObject;
        return View(cp2);

    }

    public IActionResult ChangeLanguage(string culture)
    {
        Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName,
            CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
            new CookieOptions() { Expires = DateTimeOffset.UtcNow.AddYears(1) });

        return Redirect(Request.Headers["Referer"].ToString());
    }
   
    
    public async Task<IActionResult> DetailedProducts(int id)
    {
        CartCommentProduct cc = new CartCommentProduct();
        var shoppingobje = cc.ShoppingCart;
        var commentobje = cc.Comment;
        var productobje = cc.Product;

        shoppingobje = new()
        {
            ProductId = id,
            Product = await _context.Products.Include(k => k.Category).FirstOrDefaultAsync(m => m.ID == id),
        };
        commentobje = new()
        {
            ProductId = id,
        };
        

        productobje = new()
        {
            ProductComments = await _context.Comments.Where(a => a.ProductId == id).Include(p => p.User)?.ToListAsync(),
        };
        cc.ShoppingCart = shoppingobje;
        cc.Comment = commentobje;
        cc.Product = productobje;

        return View(cc);
    }

    
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

WP/Views/Home/DetailedProducts.cshtml
@model WP.Models.CartCommentProduct
@inject ILanguageService language
@{
    ViewData["Title"] = "Product Detail Page";
}


<div class="container mt-5">
    <div class="row" style="">
        <div class="col-6" style="padding-right:10px">
            <div class="card" style="height:">
                <img class="card-img-top" src="@Model.ShoppingCart.Product.Image" alt="Card image cap">
            </div>
        </div>
        <div class="col-6">
            <div class="row">
                <h3>
                    @Model.ShoppingCart.Product.Title
                </h3>
            </div>
            <div class="row" style="margin-top:20px;">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="star-st">
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star-fill"></i>
                        <i class="bi bi-star"></i>
                    </div>
                    <h5>
                        @*                       @{

                                if (Model.ShoppingCart.Product.ProductComments.Count > 0)
                                {
                                    @Model.ShoppingCart.Product.ProductComments.Count @:comments
                                }
                                else
                                {
                                    @:0 comments
                                }
                            }*@

                    </h5>
                </div>
            </div>
            <div class="row" style="margin-top:20px;">
                <span style="font-weight:bold;font-size:32px;">
                    $@Model.ShoppingCart.Product.Price
                </span>
            </div>
            <div class="mt-3">
                <span style="font-weight:100">
                    @Model.ShoppingCart.Product.Description
                </span>
            </div>
            <div class="row mt-5">
                <div class="col-12 mt-3">
                    <div class="row">
                        <div class="col-6">
                            <div class="row">
                                <div class="col-5" style="font-weight:bold;">
                                    @language.Getkey("Category")
                                </div>
                                <div class="col-2">
                                    :
                                </div>
                                <div class="col-5">
                                    @Model.ShoppingCart.Product.Category.CategoryName
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 mt-3">
                    <div class="row">
                        <div class="col-6">
                            <div class="row">
                                <div class="col-5" style="font-weight:bold;">
                                    @language.Getkey("Color")
                                </div>
                                <div class="col-2">
                                    :
                                </div>
                                <div class="col-5">
                                    @Model.ShoppingCart.Product.Color
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 mt-3">
                    <div class="row">
                        <div class="col-6">
                            <div class="row">
                                <div class="col-5" style="font-weight:bold;">
                                    @language.Getkey("Brand")
                                </div>
                                <div class="col-2">
                                    :
                                </div>
                                <div class="col-5">
                                    @Model.ShoppingCart.Product.Brand
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <form method="post" asp-action="AddProductToCart" asp-controller="Cart">
                <input hidden asp-for="@Model.ShoppingCart.ProductId" />
                <div class="row mt-5">
                    <div class="col-6">
                        <input class="form-control" min="1" type="number" asp-for="@Model.ShoppingCart.Count" />
                    </div>
                    <button class="btn" style="background-color: #ff9117;margin-top:20px;">@language.Getkey("Add to Cart")</button>
                </div>
            </form>

        </div>
    </div>


</div>

<div class="container" style="margin-top:40px;border:0.2px solid gray;border-radius:5px;margin-top:40px;width:90%;padding-bottom:80px;padding-left:20px;padding-right:20px;">
    <div class="row" style="display:flex;justify-content:center;font-size:32px;margin-top:20px;padding-top:30px;">
        @language.Getkey("All Comments")
    </div>
    <form method="post" asp-action="AddCommentToProduct" asp-controller="Comment">
        <input hidden asp-for="@Model.Comment.ProductId" />
        <div>
            <div class="row mt-3" style="margin-top:60px;">
                <div class="col-5" style="display:flex;justify-content:space-between;">
                    <input class="form-control" asp-for="@Model.Comment.commentString" type="text" placeholder="@language.Getkey("What do you think?")" style="border-radius: 10px; background-color: #eeeeee;height:40px;" />
                </div>
                <div class="col-4">
                </div>
                <div class="col-2">
                    <button type="submit" class="btn btn-primary" style="width:150px">@language.Getkey("Add")</button>
                </div>
                <div>

                </div>

            </div>
    </form>

    @{
       
            foreach (var item in Model.Product.ProductComments)
            {
                <div class="row" style="margin-top:40px;padding:3px;">
                    <div class="col-1 mt-4">
                        <img src="~/img/defaultavatar.png" style="width:40px;height:40px;" />
                    </div>
                    <div class="col-6" style="background-color:#eeeeee;border-radius:15px;margin-left:1em;padding:15px;">
                        @item.commentString
                    </div>
                    <div class="col-2 mt-3">
                        @item.User
                    </div>
                    <div class="col-2 mt-2">
                        @item.commentDate
                    </div>
                </div>
            }
        }
          
        
    
    
    
   

</div>

WP/Views/Home/FilteredProducts.cshtml
@model WP.Models.CategoriesProducts
@inject ILanguageService language


<div class=" mt-5">
    <div class="row" style="width:100%;">
        <div class="col-lg-2 mt-5"style="padding-left:4rem">
            <div class="card mt-3" style="width:14rem;border-radius:15px;">
                <div class="card-body">
                    <h4 style="color:black;">Categories</h4>
                    <hr style="background-color:#fed700;margin-top:1em;" />
                    
                    <div class="row">
                        <div class="col-lg-12">
                            <a asp-controller="Home" asp-action="Index" style="width:150px;" class="btn btn-primary mx-2">All Products</a>
                            <hr />
                        </div>
                    </div>
                    @{
                        foreach (var item in Model.categories)
                        {
                            <div class="row">
                                <div class="col-lg-12">
                                    <a asp-controller="Home" asp-action="FilteredProducts" style="width:150px;" asp-route-id="@item.CategoryId" class="btn btn-primary mx-2">@item.CategoryName</a>
                                    <hr />
                                </div>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
        <div class="col-lg-10" style="padding-left:40px;">
            <div class="row">
                <div class="col-lg-12">
                    <div class="row">

                        <div class="col-lg-4">
                            <h5>
                                @ViewData["name"]
                            </h5>

                        </div>
                    </div>
                    <hr style="background-color:#fed700" />
                    <div class="row">
                    

                        <div class="col-lg-12 d-flex justify-content-end">
                            @using (Html.BeginForm("FilteredProducts", "Home"))
                            {
                        
                            <input type="submit" name="bname" value="Ascending" class="btn" style="background-color:orange;color:white;" />
                            }

                            @using (Html.BeginForm("FilteredProducts", "Home", new { id = ViewData["categoryid"] }))
                            {
                        
                            <input type="submit" name="bname" value="Descending" class="btn ml-1" style="background-color:purple;color:white;" />
                            }
                        </div>
                        

                    </div>
                    <div class="row">
                    
                    
                        @{
                            foreach (var item in Model.products)
                            {
                                <div class="col-4 mt-3" id="product-card">
                                    <div class="card">
                                        <a asp-action="DetailedProducts" asp-controller="Home" asp-route-id="@item.ID">
                                            <img class="card-img-top" src="@item.Image" alt="Card image cap">
                                            <div class="card-body">
                                                <h5 class="card-title">
                                                    @item.Title
                                                </h5>
                                                <p class="card-text" style="font-size: 13px;color:black !important;font-weight:100;">
                                                    @{
                                                        int length;
                                                        if (item.Description.Length > 65)
                                                        {
                                                            length = 65;
                                                        }
                                                        else
                                                        {
                                                            length = item.Description.Length;
                                                        }
                                                    }
                                                    @item.Description.Substring(0, length)
                                                    @{
                                                        if (item.Description.Length > 40)
                                                        {
                                                            @:...
                                                        }

                                                    }

                                                </p>
                                                <div class="" style="display:flex;justify-content:space-between">
                                                    <h4>
                                                        $@item.Price
                                                    </h4>
                                                    <div class="row">
                                                        <div class="col-12" style="display:flex;justify-content:flex-start">
                                                            <h6 style="font-weight:bold;margin-top:0.1em;color:black !important;">
                                                            </h6>
                                                            <span class="" style="font-weight:100;margin-left:0.4em;color:black !important;">

                                                            </span>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row mt-4">
                                                    <div class="row" style="display:flex;justify-content:space-between;">
                                                        <div class="col-12" style="display:flex;justify-content:flex-start">
                                                            <i class="bi bi-cart-check-fill" style="font-size: 18px; color: black; background-color: #c1e126;padding:3px;">
                                                            </i>
                                                            <div class="hvr-spn" style="background-color: #2b353d;color:white;padding:3px">
                                                                <span style="padding:6px;margin-top:3em;">
                                                                    @language.Getkey("Add To Cart")
                                                                </span>
                                                            </div>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>